# Generated by Django 4.1.7 on 2023-07-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.IntegerField()),
                ('y_value', models.FloatField()),
            ],
        ),
    ]
