# Generated by Django 4.2.2 on 2023-07-06 16:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
