# Generated by Django 4.2.2 on 2023-07-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_datapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
